### ISSUE TITLE
[SCAN] sub-03_ses-002

### ISSUE THREAD

**Issue by sangfrois** [courtois-neuromod/mariostars#17]
### Setup

- [X] biopac
- [X] sensimetrics
- [ ] eyetracker
- [X] game controller

### general notes

eye tracker pupil capture stream would freeze

### task-mariostars_run-01 completion

- [X] series was completed.

### task-mariostars_run-02 completion

- [X] series was completed.

### task-mariostars_run-03 completion

- [ ] series was completed.

### task-mariostars_run-04 completion

- [ ] series was completed.

### task-mariostars_run-05 completion

- [ ] series was completed.
