### ISSUE TITLE
[SCAN] sub-06_ses-007

### ISSUE THREAD

**Issue by sangfrois** [courtois-neuromod/mariostars#18]
### Setup

- [X] biopac
- [X] sensimetrics
- [ ] eyetracker
- [X] game controller

### general notes

Calibration would not function properly. No red dot shown.

### task-mariostars_run-01 completion

- [X] series was completed.

### task-mariostars_run-01 issues

eyetracking issues (crash, pupil loss)

### task-mariostars_run-01 notes

No eye tracking data whatsoever

### task-mariostars_run-02 completion

- [X] series was completed.

### task-mariostars_run-02 issues

eyetracking issues (crash, pupil loss)

### task-mariostars_run-02 notes

eyetracking data acquired, but no calibration

### task-mariostars_run-03 completion

- [X] series was completed.

### task-mariostars_run-03 issues

eyetracking issues (crash, pupil loss)

### task-mariostars_run-03 notes

eyetracking data acquired, but no calibration

### task-mariostars_run-04 completion

- [X] series was completed.

### task-mariostars_run-04 notes

eyetracking data acquired, but no calibration
participant want to stop. their hands hurt

### task-mariostars_run-05 completion

- [ ] series was completed.
