### ISSUE TITLE
[SCAN] sub-03_ses-003

### ISSUE THREAD

**Issue by sangfrois** [courtois-neuromod/mariostars#20]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker
- [X] game controller

### general notes

B button press is undermined by the flexibility of the game controller material. Leading to difficulties in doing some in game actions.

### task-mariostars_run-01 completion

- [X] series was completed.

### task-mariostars_run-01 issues

physio signal quality issue

### task-mariostars_run-01 notes

Pulse signal is saturated by high frequency noise. No apparent explanation. Equipement was properly placed and pulse was visible before starting acquisition.

### task-mariostars_run-02 completion

- [ ] series was completed.

### task-mariostars_run-03 completion

- [ ] series was completed.

### task-mariostars_run-04 completion

- [ ] series was completed.

### task-mariostars_run-05 completion

- [ ] series was completed.
