### ISSUE TITLE
[SCAN] sub-05_ses-002

### ISSUE THREAD

**Issue by me-pic** [courtois-neuromod/mariostars#39]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker
- [X] game controller

### general notes

All physiological signals looked good during the set-up. 

A lot of warnings (frame XX dropped) during the runs in the terminal 

### task-mariostars_run-01 completion

- [X] series was completed.

### task-mariostars_run-01 notes

Inside the MRI tunnel (before the run started): small R peaks in the ECG signal / big T wave
During the run: R peaks barely visible in the ECG data.

### task-mariostars_run-02 completion

- [X] series was completed.

### task-mariostars_run-02 notes

Between run-01 and 02: small R peaks in the ECG signal / big T wave
During the run: R peaks barely visible in the ECG data.

### task-mariostars_run-03 completion

- [X] series was completed.

### task-mariostars_run-03 issues

eyetracking issues (crash, pupil loss)

### task-mariostars_run-03 notes

The program crashed during the eyetracker calibration. We had to restart the task.

Between run-02 and 03: small R peaks in the ECG signal / big T wave
During the run: R peaks difficult to observed in the ECG data. Some plateaus in the EDA signal.

### task-mariostars_run-04 completion

- [X] series was completed.

### task-mariostars_run-04 notes

Between run-03 and 04: small R peaks in the ECG signal / big T wave; plateaus in the EDA signal

During the run: R peaks difficult to observed in the ECG data. Some plateaus in the EDA signal. Acknowledge froze for an instant when trying to autoscale the EDA waveform, although it didn't seemed to affect the time course.

### task-mariostars_run-05 completion

- [X] series was completed.

### task-mariostars_run-05 notes

Between run-04 and run-05:  small R peaks in the ECG signal / big T wave; PPG/EDA/respiratory signals looked ok !

**Comment by me-pic** [comment]
**task-mariostars_run-06 completion**
- [X]  series was completed

**task-mariostars_run-06 issues**


**task-mariostars_run-06 notes**

Between run-05 and run-06: small R peaks in the ECG signal / big T wave
During the run: R peaks difficult to observed in the ECG data. Some plateaus in the EDA signal.

**Comment by me-pic** [comment]
**task-mariostars_run-07 completion**
- [X]  series was completed

**task-mariostars_run-07 issues**


**task-mariostars_run-07 notes**

Between run-06 and run-07: small R peaks in the ECG signal / big T wave
During the run: R peaks difficult to observed in the ECG data. Plateaus in the EDA signal

**Comment by me-pic** [comment]
**task-mariostars_run-08 completion**
- [X]  series was completed

**task-mariostars_run-08 issues**

**task-mariostars_run-08 notes**

Between run-07 and run-08: small R peaks in the ECG signal / big T wave
During the run: R peaks difficult to observed in the ECG data; plateaus in the EDA signal; high frequency noise in the ECG signal towards the end of the run

**Comment by me-pic** [comment]
**task-mariostars_run-09 completion**
- [X]  series was completed

**task-mariostars_run-09 issues**

eyetracking issue (crash)

**task-mariostars_run-09 notes**

The program crashed during the eyetracker calibration. We had to restart the task.

Between run-09 and run-10: small R peaks in the ECG signal / big T wave
During the run: AcqKnowledge froze for a short moment (not responding).

**Comment by me-pic** [comment]
**task-mariostars_run-10 completion**
- [X]  series was completed

**task-mariostars_run-10 issues**

**task-mariostars_run-10 notes**

Between run-09 and run-10: small R peaks in the ECG signal / big T wave
During the run: flat PPG; lot of noise in the EDA signal, especially towards the end of the run
