### ISSUE TITLE
[SCAN] sub-06_ses-001

### ISSUE THREAD

**Issue by me-pic** [courtois-neuromod/mariostars#4]
### Setup

- [X] biopac
- [X] sensimetrics
- [ ] eyetracker
- [X] game controller

### general notes

Unable to set up the eye tracker. After 10min trying to set it up, we've decided to continue without it for the session.

### task-mariostars_run-01 completion

- [X] series was completed.

### task-mariostars_run-01 issues

eyetracking issues (crash, pupil loss), physio signal quality issue

### task-mariostars_run-01 notes

Eyetracking issue: see general notes

Physio signal: PPG signal was noisy, EDA values increased when the scan started (from below 5 to approx. 10)

Other: Sub asked to raise the volume of the sound

### task-mariostars_run-02 completion

- [X] series was completed.

### task-mariostars_run-02 issues

eyetracking issues (crash, pupil loss), physio signal quality issue

### task-mariostars_run-02 notes

Eyetracking issue: see general notes

Other: Sub asked to raise the volume of the sound (they said they could barely hear anything)

### task-mariostars_run-03 completion

- [X] series was completed.

### task-mariostars_run-03 issues

eyetracking issues (crash, pupil loss)

### task-mariostars_run-03 notes

Eyetracking issue: see general notes

Other: sub said that the volume was still not that high even if it was maximum. Code crashed, had to restart the command in the terminal

### task-mariostars_run-04 completion

- [X] series was completed.

### task-mariostars_run-04 issues

eyetracking issues (crash, pupil loss)

### task-mariostars_run-04 notes

Eyetracking issue: see general notes

### task-mariostars_run-05 completion

- [ ] series was completed.
