### ISSUE TITLE
[SCAN] sub-05_ses-003

### ISSUE THREAD

**Issue by RainyFields** [courtois-neuromod/mariostars#40]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker
- [X] game controller

### task-mariostars_run-01 completion

- [X] series was completed.

### task-mariostars_run-01 notes

EDA signal is not stable

### task-mariostars_run-02 completion

- [X] series was completed.

### task-mariostars_run-02 notes

EDA signal was not stable
python crashed after run 02

### task-mariostars_run-03 completion

- [X] series was completed.

### task-mariostars_run-03 notes

EDA looks normal after checking the connection. 
have to restart the program starting from run 03
something wrong with the eye tracker: 
subject 05 rolled his eyes before the calibration but it seemed like he did not precisely follow the dots on the screen. The clusters did not appear on the screen after the calibration either. 
the program crashed after run 03

### task-mariostars_run-04 completion

- [x] series was completed.

### task-mariostars_run-04 notes

we restarted the program and the eyetracker seems working well for run_04

### task-mariostars_run-05 completion

- [X] series was completed.

### task-mariostars_run-05 notes

eyetracker the same situation as in run 03

### task-mariostars_run-06 completion

- [X] series was completed.

### task-mariostars_run-06 notes

eyetracker the same situation as in run 03

### task-mariostars_run-07 completion

- [X] series was completed.

### task-mariostars_run-07 notes

eyetracker the same situation as in run 03

a lot of frames dropped in the end(after 10mins scanning time)
the game continues after 15 mins scanning time

### task-mariostars_run-08 completion

- [X] series was completed.

### task-mariostars_run-08 notes

eyetracker the same situation as in run 03

a lot of frames dropped in the end(after 10mins scanning time)
the game continues after 15 mins scanning time

program crashed after calibration for run 09

### task-mariostars_run-09 completion

- [X] series was completed.

### task-mariostars_run-09 notes

eyetracker the same situation as in run 03 [even with restart the program]

### task-mariostars_run-10 completion

- [X] series was completed.

### task-mariostars_run-10 notes

eyetracker the same situation as in run 03

**Comment by RainyFields** [comment]
the eyetracker is fine -- multiple windows opened and the one worked was hidden below
