### ISSUE TITLE
[SCAN] sub-05_ses-005

### ISSUE THREAD

**Issue by RainyFields** [courtois-neuromod/mariostars#42]
### Setup

- [X] biopac
- [X] sensimetrics
- [ ] eyetracker
- [X] game controller

### general notes

the connection to the eyetracker got detached during the break.

### task-mariostars_run-01 completion

- [X] series was completed.

### task-mariostars_run-02 completion

- [X] series was completed.

### task-mariostars_run-03 completion

- [X] series was completed.

### task-mariostars_run-04 completion

- [X] series was completed.

### task-mariostars_run-04 notes

The scanner stopped after the requisition time but the progress bar on the terminal only reached 52%.\
=> it turns out that we did not stop the scanner after run 03. so no imaging data for run 04. 

### task-mariostars_run-05 completion

- [X] series was completed.

### task-mariostars_run-05 notes

because of the previous mistake, run 05 was using MRI sequences for run 04. Imaging file should be rename from run04 to run05. [we do not have imaging data for run04]

For subsequent runs [run06] , the run numbers are synchronized between the tsv/loggings and the imaging file. 

### task-mariostars_run-06 completion

- [X] series was completed.
